source "https://rubygems.org"

gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "rake"

gem "require_all"
gem "sqlite3"
gem "pry"
gem "faker"

gem "colorize"
gem "activerecord-reset-pk-sequence"
gem "tty-prompt"
gem "tty-table"
gem "tty-box"

